src/Entity/Vol.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping\Index;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VolRepository")
 */
class Vol
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     */
    private $depart;

    /**
     * @ORM\Column(type="string")
     */
    private $arrivee;

    /**
     * @ORM\Column(type="datetime")
     */
    private $heure_depart;

    /**
     * @ORM\Column(type="datetime")
     */
    private $heure_arrivee;

    /**
     * @ORM\Column(type="time")
     */
    private $duree;


    /**
     * @ORM\Column(type="integer")
     */
    private $numero_vol;

    /**
     * @ORM\Column(type="integer")
     */
    private $prix;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Aeroports" )
     * @ORM\JoinColumn(name="depart", referencedColumnName="ville")
    */
    private $depart_aeroports;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Aeroports")
     * @ORM\JoinColumn(name="arrivee", referencedColumnName="ville")
     */
    private $arrivee_aeroports;

    /**
     * @ORM\Column(type="string")
     */
    private $compagnies;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Compagnies")
     * @ORM\JoinColumn(name="compagnies", referencedColumnName="nom")
     */
    private $vol_compagnies;

    /**
     * @ORM\Column(type="integer")
     */
    private $places = 50;


    public function getId(): ?int
    {
        return $this->id;
    }


    public function getDepart(): ?string
    {
        return $this->depart;
    }

    public function setDepart(string $depart): self
    {
        $this->depart = $depart;

        return $this;
    }

    public function getArrivee(): ?string
    {
        return $this->arrivee;
    }

    public function setArrivee(string $arrivee): self
    {
        $this->arrivee = $arrivee;

        return $this;
    }
    

    public function getHeureDepart(): ?\DateTimeInterface
    {
        return $this->heure_depart;
    }

    public function setHeureDepart(\DateTimeInterface $heure_depart): self
    {
        $this->heure_depart = $heure_depart;

        return $this;
    }

    public function getHeureArrivee(): ?\DateTimeInterface
    {
        return $this->heure_arrivee;
    }

    public function setHeureArrivee(\DateTimeInterface $heure_arrivee): self
    {
        $this->heure_arrivee = $heure_arrivee;

        return $this;
    }

    public function getDuree(): ?\DateTimeInterface
    {
        return $this->duree;
    }

    public function setDuree(\DateTimeInterface $duree): self
    {
        $this->duree = $duree;

        return $this;
    }


    public function getNumeroVol(): ?int
    {
        return $this->numero_vol;
    }

    public function setNumeroVol(int $numero_vol): self
    {
        $this->numero_vol = $numero_vol;

        return $this;
    }


    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }


    public function getDepartAeroports(): ?Aeroports
    {
        return $this->depart_aeroports;
    }

    public function setDepartAeroports(?Aeroports $depart_aeroports): self
    {
        $this->depart_aeroports = $depart_aeroports;

        return $this;
    }

    public function getArriveeAeroports(): ?Aeroports
    {
        return $this->arrivee_aeroports;
    }

    public function setArriveeAeroports(?Aeroports $arrivee_aeroports): self
    {
        $this->arrivee_aeroports = $arrivee_aeroports;

        return $this;
    }

    public function getCompagnies(): ?string
    {
        return $this->compagnies;
    }

    public function setCompagnies(string $compagnies): self
    {
        $this->compagnies = $compagnies;

        return $this;
    }

    public function getVolCompagnies(): ?Compagnies
    {
        return $this->vol_compagnies;
    }

    public function setVolCompagnies(Compagnies $vol_compagnies): self
    {
        $this->vol_compagnies = $vol_compagnies;

        return $this;
    }

    public function getPlaces(): ?int
    {
        return $this->places;
    }

    public function setPlaces(int $places): self
    {
        $this->places = $places;

        return $this;
    }

    public function getDateDeparts(): ?Aeroports
    {
        return $this->dateDeparts;
    }

    public function setDateDeparts(?Aeroports $dateDeparts): self
    {
        $this->dateDeparts = $dateDeparts;

        return $this;
    }


    
}

src/Controller/RechercheController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\JsonResponse;
use App\Entity\Vol;
use App\Entity\Aeroports;
use App\Entity\Compagnies;

class RechercheController extends AbstractController
{
    /**
     * @Route("/recherche", name="recherche")
     */
    public function recherche(Request $request)
    {
          // On vérifie que l'utilisateur dispose bien du rôle ROLE_AUTEUR
   /* if (!$this->get('security.authorization_checker')->isGranted('ROLE_ADMIN')) {
      // Sinon on déclenche une exception « Accès interdit »
      throw new AccessDeniedException('Accès limité aux auteurs.');
    }*/
        $em_airports = $this->getDoctrine()->getRepository(Aeroports::class);
        $em_compagnies = $this->getDoctrine()->getRepository(Compagnies::class);
        $data = $request->request->all();
        if($request->getMethod() == "POST" && $request->isXmlHttpRequest())
        {
            if($data['dom'] == "compagnies")
            {
                $msg = $em_compagnies->findByCompagnies($data['val']);
            }
            else
            {
                $msg = $em_airports->findByVille($data['val']);
            }
            
            $view = $this->renderView("Recherche/affiche_ville.html.twig", ["aeroports" => $msg]);
            dump($msg);
            return new JsonResponse(["view" => $view]);
        }
    	return $this->render('Recherche/accueil.html.twig');
    }




    /**
     * @Route("/recherche/view", name="recherche/view")
     */
    public function rechercheView(Request $request)
    {
    	$em = $this->getDoctrine()->getRepository(Vol::class);
        $data = $request->request->all();
    		
    	if(($request->getMethod() == "POST") && ($request->isXmlHttpRequest()))
    	{
    		// recherche des vol pour le cas de retour + recaptilatutif de vol aller choisi
    		if(isset($_REQUEST["volaller"]))
    		{
                dump($data);
    			// Récapituatif de vol aller choisi pour 3 cas ("vol direct", "avec un escale", "avec 2 escale")
    			$volaller = $em->find($data["volaller"]);
    			if(isset($_REQUEST["es1"]))
    			{
    				$volaller2 = $em->find($data["es1"]);    			 	
    			 	if(isset($_REQUEST["es2"]))
    			 	{    			 		
	    			 	$volaller3 = $em->find($data["es2"]);
	    			 	$volaller = array('0' => $volaller, '1' => $volaller2, '2' => $volaller3);
    			 	}
    			 	else{ $volaller = array('0' => $volaller, '1' => $volaller2); }    			 	
    			}

    			// recherche des  vols disponible le cas de retour	
                if(isset($data['filtre']))
                    { $vols = $em->findByVolDirect($data['da'], $data['va'], $data['vd'], $data['np']); }
                else
                {
                    $arrivee_esc = date("Y-m-d",strtotime($data['da']."+ 2 days"));
                    $resultat = $em->findByEscaleVol($data['da'], $arrivee_esc, $data['np']);
                    $vols = $this->filtreEscale($resultat, $data['va'], $data['vd']); 
                }			
				

				// return vols dispo ou pas   		
    			if($vols){
    				$view = $this->renderView('Recherche/vols_aller_retour.html.twig', ["vols"=>$vols, "volaller"=>$volaller, "recap"=>$data]);
    			}
    			else{ $view = $this->renderView('Recherche/aucun_vol.html.twig'); }
    			
				return new JsonResponse(array('Success' => true, 'code' => 200, "view" => $view));				
    		}

            dump($data);
    		// Recherche des vols aller disponibles
            if(isset($data['filtre'])){ $vols = $em->findByVolDirect($data['dd'], $data['vd'], $data['va'], $data['np']); }
            else
            {
                $depart_esc = date("Y-m-d",strtotime($data['dd']."+ 2 days"));
                $resultat = $em->findByEscaleVol($data['dd'], $depart_esc, $data['np']);
                $vols = $this->filtreEscale($resultat, $data['vd'], $data['va']);  
            }
    		

    		if($vols){
    			if($data['da'] == "2010-01-01")
    				$view = $this->renderView('Recherche/vols_aller_retour.html.twig', ["vols"=>$vols, "recap"=>$data]);
    			else
    				$view = $this->renderView('Recherche/vols_aller_retour.html.twig', ["vols"=>$vols, "recap"=>$data]);
    		}	    			
    		else{ $view = $this->renderView('Recherche/aucun_vol.html.twig'); }

    		return new JsonResponse(array('Success' => true, 'code' => 200, "view" => $view));
    	}
        return $this->render('Recherche/recherche.html.twig');
    }


    }

}

templates/Recherche/accueil.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<form name="recherche">
    <div class="row justify-content-center">

        <div class="form-row col-8">
            <div class="form-check form-check-inline col-2">
              <input class="form-check-input" type="radio" id="inlineCheckbox1" name="vol" value="allerretour" checked>
              <label class="form-check-label" for="inlineCheckbox1">Aller-retour</label>
            </div>
            <div class="form-check form-check-inline col-2">
              <input class="form-check-input" type="radio" id="inlineCheckbox2" name="vol" value="allersimple">
              <label class="form-check-label" for="inlineCheckbox2">Aller simple</label>
            </div>
         </div>
        <div class="form-row col-8">
            <div class="form-group col-5">
                <label for="depart">Depart</label>
                <input type="text" class="form-control dropdown-toggle" data-toggle="dropdown" value="paris" id="depart" name="vd" data="aeroports" placeholder="Depart" autocomplete="on" required>
                <!-- <ul class="list-group" id="liste_depart">   </ul> -->
                <ul class="dropdown-menu scrollable-menu" role="menu" id="liste_depart">
                    <!-- <li><a href="#">Action</a></li> -->
                </ul>

            </div>
            <div class="form-group col-1">
                <label for="h">  </label>
                <label>  </label>
            </div>
            <div class="form-group col-5">
                <label for="destination">Destination</label>
                <input type="text" class="form-control" name="va" id="arrivee" value="colombo" data="aeroports" placeholder="arrive" required>
                <ul class="dropdown-menu scrollable-menu" role="menu" id="liste_arrivee">
                    <!-- <li><a href="#">Action</a></li> -->
                </ul>
                <!-- <ul class="list-group" id="liste_arrivee"> </ul> -->
            </div>
        </div>
        
        <div class="form-row col-8">
            <div class="form-group col-5">
                <label for="Heuredepart">Date de depart</label>
                <input type="date" class="form-control" name="dd" value="2019-04-27" required>
            </div>
            <div class="form-group col-1"></div>
            <div class="form-group col-5" id="radiosimple">
                <label for="Heurearrivee">Date d'arrivée</label>
                <input type="date" class="form-control" name="da" value="2019-04-30" required>
            </div>
        </div>

        <div class="form-row col-8">
            <div class="form-group col-4">
                <input type="number" class="form-control" name="np" value="3">
            </div>
            <div class="form-group col-1"></div>
            <div class="form-check form-check-inline col-2">
              <input class="form-check-input" type="checkbox" id="filtre" name="filtre" value="direct">
              <label class="form-check-label" for="filtre">Direct</label>
            </div>
        </div>

        
        
        <div class="form-row col-8">
            <div class="form-group col-6">
                <button type="submit" class="form-control btn-delete btn-primary" id="recherche_vol"> Rechercher </button>
            </div>
        </div>
        

    </div>
</form>





{% endblock %}

{% block javascripts %}


$(document).on("submit", "form[name=recherche]", function(e){
    e.preventDefault();
    var data = $(this).serialize();
    window.location.href= "{{path('recherche/view')}}?&" + data;
});


$(document).on("change", "input[type=radio]", function(){
    var valradio = $(this).attr("value");
    if(valradio == "allersimple")
        $("#radiosimple").addClass("d-none").children("input").attr("value", "2010-01-01");
    else
        $("#radiosimple").removeClass("d-none").children("input").attr("value", "");
});


$(document).on("keyup", "input[type=text]", function(){
    var valeur = $(this).val();
    var name = $(this).attr("id");
    var dom = $(this).attr("data");
    console.log(valeur);
    
    if(valeur.length > 2)
    {
        var request = $.ajax({
            url : "{{ path('recherche') }}",
            method: "POST",
            data: "&val=" + valeur + "&dom=" + dom
        });
        request.done(function(msg){
        console.dir(msg);
           $("#liste_" + name).html(msg.view);
        });
    }
});

$(document).on("click", ".listeville", function () {
    $(this).parent().parent().children("input").val($(this).html());
    $(this).parent().html("");
});

 $(document).on("click", ".list-group-item", function () {
    $(this).parent().parent().children("input").val($(this).html());
    $(this).parent().html("");
});

{% endblock %} 

templates/Recherche/affiche_ville.html.twig
{% for data in aeroports %}
	<li class="listeville">{{data.ville}}</li>
{% endfor %}

templates/Recherche/aucun_vol.html.twig
<div class="row justify-content-center">				
	<label class="col-12 text-center">Aucune Vols correspondants à votre recherche veuillez modifier votre recherche </label>
	<button class="btn btn-warning col-4" action="{{path('recherche')}}"> Modifier </button>
</div>
	

templates/Recherche/detail_vol_escale.html.twig
<div class="form-row border text-center mt-2 pt-3 col-8">
            
    <div class="form-group col-5"> 
        <label class="col-12 "> {{vol[0].depart | upper }} départ à {{vol[0].heureDepart | date("H:i") }} </label>
        <label class="col-12"> le {{vol[0].heureDepart | localizeddate('none', 'none', 'none', null, 'd MMM YYYY HH') }} </label>
    </div>
    <div class="form-group col-5">
        <label class="col-12"> {{vol[0].arrivee | upper }} arrivée à {{vol[1].duree | date("H:i") }} </label>
        <label class="col-12"> le {{vol[0].heureArrivee | localizeddate('none', 'none', 'none', null, 'd MMM YYYY HH')}} </label>
    </div>

    <div class="form-group col-2">
        <label class="col-12"> Duree {{vol[0].duree | date("H:i") }} </label>  
        <label class="col-12"> N° vol : {{ vol[0].numeroVol }} </label>                     
    </div>

    <div class="form-group col-12">
        <label class="col-12"> Durée de l'escale </label>
        <label class="col-12"> 
            {% set diffdate = date(vol[1].heureDepart).diff(date(vol[0].heureArrivee)) %}
            {% if diffdate.d %}
                {{ diffdate.d }}J {{ diffdate.h }}h{{ diffdate.i }}
            {% else %}
                {{ diffdate.h }}h{{ diffdate.i }}
            {% endif %}
        </label>
    </div>

    <div class="form-group col-5"> 
        <label class="col-12 "> {{vol[1].depart | upper }} départ à {{vol[1].duree | date("H:i") }} </label>
        <label class="col-12"> le {{vol[1].heureDepart | localizeddate('none', 'none', 'none', null, 'd MMM YYYY HH') }} </label>
    </div>
    <div class="form-group col-5">
        <label class="col-12"> {{vol[1].arrivee | upper }} arrivée à {{vol[1].duree | date("H:i") }} </label>
        <label class="col-12"> le {{vol[1].heureArrivee | localizeddate('none', 'none', 'none', null, 'd MMM YYYY HH')}} </label>
    </div>

    <div class="form-group col-2">
        <label class="col-12"> Duree {{vol[1].duree | date("H:i") }} </label>
        <label class="col-12"> N° vol : {{ vol[1].numeroVol }} </label>                      
    </div>   

</div>

templates/Recherche/vol.html.twig
{% if (vol | length == 1) %}

    <div class="row bg-light border mt-4 pt-1 detailVolAller" id="{{ vol.id }}">
        <div class="col-2">
            <label class="col-12"> DATE </label>
            <label class="col-12"> {{vol.heureDepart | date("d/m/Y") }} </label> 
        </div>
        <div class="col-2">
            <label class="col-12"> TRAJET </label>
            <label class="col-12"> {{vol.depart}} - {{vol.arrivee}}</label> 
        </div>
        <div class="col-2">
            <label class="col-12"> DÉPART </label>
            <label class="col-12"> {{vol.heureDepart | date("H:i") }} </label> 
        </div>
        <div class="col-2">
            <label class="col-12"> ARRIVÉE </label> 
            <label class="col-12"> {{vol.heureArrivee | date("H:i")}} </label> 
        </div>
        <div class="col-2">
            <label class="col-12"> TARIF </label> 
            <label class="col-12" id="tariftype">{{ recap.catb |upper }}</label> 
        </div>
        <div class="col-2">
            <label class="col-12"> PRIX </label> 
            
            <label class="col-12"> 
                {% if recap.catb == "express" %} {{vol.prix * 0.9}} € 
                {% elseif recap.catb == "flex" %} {{vol.prix * 1.5 }} €
                {% else %} {{vol.prix }} €
                {% endif %}
            </label> 
        </div>
    </div>    

{% elseif (vol|length >= 2) %}

    {% if (vol|length == 2) %}
        <div class="row bg-light border mt-4 pt-1 detailVolAller" id="{{ vol[0].id }}&es1={{vol[1].id}}">
    {% elseif (vol|length == 3) %}
        <div class="row bg-light border mt-4 pt-1 detailVolAller" id="{{ vol[0].id }}&es1={{vol[1].id}}&es2={{vol[1].id}}">
    {% endif  %}

         <div class="col-2">
            <label class="col-12"> DATE </label>
            <label class="col-12"> {{vol[0].heureDepart | date("d/m/Y") }} </label> 
        </div>
        <div class="col-2">
            <label class="col-12"> TRAJET </label>
            <label class="col-12"> {{vol[0].depart}} - {{ vol[(vol|length)-1].arrivee }}</label> 
        </div>
        <div class="col-2">
            <label class="col-12"> DÉPART </label>
            <label class="col-12"> {{vol[0].heureDepart | date("H:i") }} </label> 
        </div>
        <div class="col-2">
            <label class="col-12"> ARRIVÉE </label> 
            <label class="col-12"> {{vol[(vol|length)-1].heureArrivee | date("H:i")}} </label> 
        </div>
        <div class="col-2">
            <label class="col-12"> TARIF </label> 
            <label class="col-12" id="tariftype">{{ recap.catb |upper }}</label> 
        </div>
        <div class="col-2">
            <label class="col-12"> PRIX </label> 
            <label class="col-12">
                {% if (vol|length == 2) %}
                    {% if recap.catb == "express" %} {{ (vol[0].prix + vol[1].prix) * 0.9}} € 
                    {% elseif recap.catb == "flex" %} {{ (vol[0].prix + vol[1].prix) * 1.5 }} €
                    {% else %} {{ (vol[0].prix + vol[1].prix) }} €  {% endif %}
                {% else %}
                    {% if recap.catb == "express" %} {{ (vol[0].prix + vol[1].prix + vol[2].prix) * 0.9}} € 
                    {% elseif recap.catb == "flex" %} {{ (vol[0].prix + vol[1].prix + vol[2].prix) * 1.5 }} €
                    {% else %} {{ (vol[0].prix + vol[1].prix + vol[2].prix ) }} €  {% endif %}
                {% endif %}
            </label> 
        </div>     

       
    </div>

{% endif %}

templates/Recherche/vols_aller_retour.html.twig
<div class="row mb-4 border-top border-bottom">
    <div class="col-3 border-right">SNIR AIRLINES </div>
    <div class="col-3 border-right"> 
        <label class="col-12 "> {{ recap.dd | localizeddate('none', 'none', 'none', null, 'd MMM') |upper }} </label>
        <h5 class="col-12"> {{ recap.vd}} -> {{ recap.va }} </h5>
    </div>
    {% if recap.vol != "allersimple" %}
     <div class="col-3 border-right typevol" data-typevol="{{recap.vol}}"> 
        <label class="col-12 "> {{ recap.da | localizeddate('none', 'none', 'none', null, 'd MMM') |upper }} </label>
        <h5 class="col-12"> {{ recap.va }} -> {{ recap.vd }} </h5>
    </div>
    {% endif %}
    <div class="col-2 border-right">
        <label class="col-12"> Passagers </label>
        <label class="col-12"> {{ recap.np }} </label>
    </div>
    <div class="col-1">
        <label class="col-12">Total </label>
        <label class="col-12"> 0.00 € </label>
    </div>
</div>



{% if recap.vol == "last" %}
    {% set vol = volaller %}
    {% include "Recherche/vol.html.twig" %}

    {% if(volaller|length == 1) %}
        {% set vaDepart = volaller.heureDepart %}
    {% else %}
        {% set vaDepart = volaller[0].heureDepart %}
    {% endif %}
   
    <div class="row mb-4 col-12 text-right text-danger" data-dateDepart="{{ vaDepart | date("d/m/Y") }}"> 
        <label class="col-12" id="changervolaller"> CHANGER ALLER </label> 
    </div>

    <div class="row mt-6">
        <label class="col-12 typevol" name="volretour"> <h2> Choissisez votre retour </h2> </label>
        <lavel class="col-12"> {{ recap.da | localizeddate('none', 'none', 'none', null, 'd MMMM YYYY') |upper }} </label>
    </div>

{% else %}

    <div class="row mt-6">
        <label class="col-12 typevol" name="volaller"> <h2> Choissisez votre aller </h2> </label>
        <lavel class="col-12"> {{ recap.dd | localizeddate('none', 'none', 'none', null, 'd MMMM YYYY') |upper }} </label>
    </div>
{% endif %}


<div id="choixvol">
    {% include "Recherche/vols_disponibles.html.twig" %}
</div>

templates/Recherche/vols_disponibles.html.twig
<div class="form-row mt-5 border text-center">
    <div class="form-group col-2"> DÉPART </div>
    <div class="form-group col-2"> </div>
    <div class="form-group col-2"> ARRIVÉE </div>
    <div class="form-group col-2"> EXPRESS <br> 7Kg/personne  </div>
    <div class="form-group col-2"> CLASSIC <br> 20Kg/personne </div>
    <div class="form-group col-2"> FLEX <br> annulation gratuit + 40Kg/personne </div>
</div>


{% for vol in vols %}

    {% if (vol |length == 1) %}
        <div class="form-row border text-center mt-2 pt-3 vol" data-id="{{ vol.id }}" data-type="direct">
            <div class="form-group col-2"> {{vol.depart | upper }} <br> {{vol.heureDepart | date("H:i") }}h  </div>
            <div class="form-group col-2 pt-2">
                {{vol.duree | date("H") }}h{{vol.duree | date("i") }}
            </div>
            <div class="form-group col-2"> {{vol.arrivee | upper }} <br> {{vol.heureArrivee | date("H:i")}} </div>
            <div class="form-group col-2 border pt-2 text-center vv" data-id="{{vol.id}}" name="express"> <input type="radio" > {{vol.prix * 0.90 }} €</div>
            <div class="form-group col-2 border pt-2 text-center vv" data-id="{{vol.id}}" name="classic"> <input type="radio" > {{vol.prix }} €</div>
            <div class="form-group col-2 border pt-2 text-center vv" data-id="{{vol.id}}" name="flex"> <input type="radio" > {{vol.prix * 1.25}} €</div>
        </div>

    {% elseif (vol |length > 1) %}

        <div class="form-row border text-center mt-2 pt-3 vol" data-type="escale">
            <div class="form-group col-2"> {{vol[0].depart | upper }} <br> {{vol[0].heureDepart | date("H:i") }}h  </div>
            <div class="form-group col-2 pt-0 mb-0"> 
                {{ vol | length }} escale  <br>
                {% set diffdate = date(vol[(vol |length)-1].heureArrivee).diff(date(vol[0].heureDepart)) %}
                {% if diffdate.d %}
                    {{ diffdate.d }}J {{ diffdate.h }}h{{ diffdate.i }}
                {% else %}
                    {{ diffdate.h }}h{{ diffdate.i }}
                {% endif %}
                <br>
                Voir détail
            </div>
            <div class="form-group col-2"> {{vol[(vol |length) -1].arrivee | upper }} <br> {{vol[(vol |length-1)].heureArrivee | date("H:i")}} </div>
            
            <div class="form-group col-2 border pt-2 text-center vv" data-id="{{ vol[0].id }}&es1={{vol[1].id}}" name="express"> <input type="radio" > {{(vol[0].prix + vol[1].prix) * 1.5 }} €</div>
            <div class="form-group col-2 border pt-2 text-center vv" data-id="{{ vol[0].id }}&es1={{vol[1].id}}" name="classic"> <input type="radio" > {{vol[0].prix + vol[1].prix }} €</div>
            <div class="form-group col-2 border pt-2 text-center vv" data-id="{{ vol[0].id }}&es1={{vol[1].id}}" name="flex"> <input type="radio" > {{ (vol[0].prix + vol[1].prix) * 2}} €</div>
        </div>


        <div class="row justify-content-center d-none">
            {% include "Recherche/detail_vol_escale.html.twig" %}
        </div>

    {% endif %}
    
{% endfor %}